// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: PcapConfig.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PcapConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  string                   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Build    string                   `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	Features *PcapConfig_PcapFeatures `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
}

func (x *PcapConfig) Reset() {
	*x = PcapConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcapConfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PcapConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcapConfig) ProtoMessage() {}

func (x *PcapConfig) ProtoReflect() protoreflect.Message {
	mi := &file_PcapConfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcapConfig.ProtoReflect.Descriptor instead.
func (*PcapConfig) Descriptor() ([]byte, []int) {
	return file_PcapConfig_proto_rawDescGZIP(), []int{0}
}

func (x *PcapConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PcapConfig) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *PcapConfig) GetFeatures() *PcapConfig_PcapFeatures {
	if x != nil {
		return x.Features
	}
	return nil
}

type PcapConfig_PcapFeatures struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Debug bool `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
}

func (x *PcapConfig_PcapFeatures) Reset() {
	*x = PcapConfig_PcapFeatures{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PcapConfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PcapConfig_PcapFeatures) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PcapConfig_PcapFeatures) ProtoMessage() {}

func (x *PcapConfig_PcapFeatures) ProtoReflect() protoreflect.Message {
	mi := &file_PcapConfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PcapConfig_PcapFeatures.ProtoReflect.Descriptor instead.
func (*PcapConfig_PcapFeatures) Descriptor() ([]byte, []int) {
	return file_PcapConfig_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PcapConfig_PcapFeatures) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

var File_PcapConfig_proto protoreflect.FileDescriptor

var file_PcapConfig_proto_rawDesc = []byte{
	0x0a, 0x10, 0x50, 0x63, 0x61, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x50, 0x63, 0x61, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x12, 0x34, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x50, 0x63, 0x61, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x50, 0x63, 0x61, 0x70, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x08, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x1a, 0x24, 0x0a, 0x0c, 0x50, 0x63, 0x61, 0x70, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x42, 0x40, 0x5a,
	0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f,
	0x70, 0x63, 0x61, 0x70, 0x2d, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2f, 0x70, 0x63, 0x61,
	0x70, 0x2d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PcapConfig_proto_rawDescOnce sync.Once
	file_PcapConfig_proto_rawDescData = file_PcapConfig_proto_rawDesc
)

func file_PcapConfig_proto_rawDescGZIP() []byte {
	file_PcapConfig_proto_rawDescOnce.Do(func() {
		file_PcapConfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_PcapConfig_proto_rawDescData)
	})
	return file_PcapConfig_proto_rawDescData
}

var file_PcapConfig_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PcapConfig_proto_goTypes = []interface{}{
	(*PcapConfig)(nil),              // 0: PcapConfig
	(*PcapConfig_PcapFeatures)(nil), // 1: PcapConfig.PcapFeatures
}
var file_PcapConfig_proto_depIdxs = []int32{
	1, // 0: PcapConfig.features:type_name -> PcapConfig.PcapFeatures
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PcapConfig_proto_init() }
func file_PcapConfig_proto_init() {
	if File_PcapConfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PcapConfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PcapConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PcapConfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PcapConfig_PcapFeatures); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PcapConfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PcapConfig_proto_goTypes,
		DependencyIndexes: file_PcapConfig_proto_depIdxs,
		MessageInfos:      file_PcapConfig_proto_msgTypes,
	}.Build()
	File_PcapConfig_proto = out.File
	file_PcapConfig_proto_rawDesc = nil
	file_PcapConfig_proto_goTypes = nil
	file_PcapConfig_proto_depIdxs = nil
}
