version: '3'

dotenv: ['.env']

tasks:

  docker-build:
    cmds:
      - >-
        docker buildx build --no-cache --file=Dockerfile
        --output={{.USER_WORKING_DIR}}/bin --target=releaser {{.USER_WORKING_DIR}}

  go-fmt:
    cmds:
      - gofumpt -l -w .

  go-gen:
    cmds:
      - go generate ./...

  build:
    dotenv: ['.env']
    cmds:
      - task: go-fmt
      - task: go-gen
      - >-
        go build
        -o bin/$TCPDUMPW_BIN_NAME
        {{if .VERBOSE}}-v -a{{end}}
        main.go

  dist:
    cmds:
      - task: build
        vars:
          VERBOSE: true
